sudo: required
language: generic
services:
- docker
branches:
  only:
  - main
addons:
  ssh_known_hosts: 13.90.253.189
before_install:
- openssl aes-256-cbc -K $encrypted_ea4d746d1f09_key -iv $encrypted_ea4d746d1f09_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# test ssh connection
- ssh -i ./deploy_key Dev@13.90.253.189 pwd

- echo Build front and api docker images for testing..
script:
- echo Run react tests..
- echo Run nodejs tests...
after_success:
- echo Building the production Docker image..
- docker build -t loaymoh99/dkr-dropoids-front ./front
- docker build -t loaymoh99/dkr-dropoids-nginx ./nginx
- docker build -t loaymoh99/dkr-dropoids-api ./api
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- echo Pushing the Docker images..
- docker push loaymoh99/dkr-dropoids-front
- docker push loaymoh99/dkr-dropoids-nginx
- docker push loaymoh99/dkr-dropoids-api
#- ssh -i ./deploy_key Dev@13.90.253.189 'cd Flicker_Clone_SWProject21_Team2/ && git clean  -d  -f . &&git reset --hard && git pull && sudo docker-compose pull && sudo docker-compose down && sudo docker-compose up -d'
- ./deploy.sh

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: bash ./deploy.sh
#   on:
#     branch: main
